#!/usr/bin/env python3
"""Build the canonical LaTeX manuscript from the reviewed Markdown source."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "paper" / "int4_attention_manuscript_draft.md"
DEFAULT_OUTPUT = ROOT / "paper" / "int4_attention_manuscript.tex"


def pandoc_fragment(markdown: str, pandoc: str, shift_headings: bool = False) -> str:
    command = [
        pandoc,
        "--from=markdown",
        "--to=latex",
        "--wrap=none",
        "--syntax-highlighting=none",
    ]
    if shift_headings:
        command.append("--shift-heading-level-by=-1")
    result = subprocess.run(
        command,
        input=markdown,
        text=True,
        check=True,
        capture_output=True,
    )
    latex = result.stdout.strip().replace("-\\/-", "--")
    return latex.replace("\\begin{figure}\n", "\\begin{figure}[!htbp]\n")


def fold_figure_captions(markdown: str) -> str:
    """Turn an image plus a following bold Figure caption into one Pandoc figure."""
    lines = markdown.splitlines()
    output: list[str] = []
    index = 0
    image_pattern = re.compile(r"^!\[[^]]*\]\(([^)]+)\)$")
    caption_pattern = re.compile(r"^\*\*Figure\s+(\d+)\.\*\*\s*(.*)$")
    while index < len(lines):
        image_match = image_pattern.match(lines[index])
        if not image_match:
            output.append(lines[index])
            index += 1
            continue

        cursor = index + 1
        if cursor < len(lines) and not lines[cursor]:
            cursor += 1
        if cursor >= len(lines):
            output.append(lines[index])
            index += 1
            continue
        caption_match = caption_pattern.match(lines[cursor])
        if not caption_match:
            output.append(lines[index])
            index += 1
            continue

        caption_parts = [caption_match.group(2)]
        cursor += 1
        while cursor < len(lines) and lines[cursor]:
            caption_parts.append(lines[cursor])
            cursor += 1
        caption = " ".join(caption_parts)
        output.append(f"![{caption}]({image_match.group(1)})")
        output.append("")
        index = cursor + 1 if cursor < len(lines) else cursor
    return "\n".join(output)


def split_manuscript(markdown: str) -> tuple[str, str]:
    abstract_marker = "## Abstract\n"
    body_marker = "## 1. Introduction\n"
    if abstract_marker not in markdown or body_marker not in markdown:
        raise ValueError("Expected Abstract and Introduction headings were not found")
    abstract_start = markdown.index(abstract_marker) + len(abstract_marker)
    body_start = markdown.index(body_marker)
    abstract = markdown[abstract_start:body_start].strip()
    body = markdown[body_start:].strip()
    return abstract, body


def normalize_headings(markdown: str) -> str:
    lines: list[str] = []
    appendix_started = False
    numbered = re.compile(r"^(##+)\s+\d+(?:\.\d+)*\.?\s+(.+)$")
    appendix = re.compile(r"^##\s+Appendix\s+[A-Z]\.\s+(.+)$")
    for line in markdown.splitlines():
        appendix_match = appendix.match(line)
        if appendix_match:
            if not appendix_started:
                lines.extend(["\\appendix", ""])
                appendix_started = True
            lines.append(f"## {appendix_match.group(1)}")
            continue
        numbered_match = numbered.match(line)
        if numbered_match:
            lines.append(f"{numbered_match.group(1)} {numbered_match.group(2)}")
            continue
        lines.append(line)
    return "\n".join(lines)


def latex_document(abstract: str, body: str) -> str:
    return rf"""% Generated by scripts/generate_int4_latex.py from the reviewed Markdown.
% Edit the Markdown source, then regenerate this file to keep both artifacts aligned.
\documentclass[10pt]{{article}}

\usepackage[letterpaper,textwidth=6.25in,textheight=9in]{{geometry}}
\usepackage{{newtxtext,newtxmath}}
\usepackage{{amsmath}}
\usepackage{{array,booktabs,calc,longtable}}
\usepackage{{graphicx}}
\usepackage{{microtype}}
\usepackage{{enumitem}}
\usepackage{{caption}}
\usepackage{{float}}
\usepackage[numbers,sort&compress]{{natbib}}
\usepackage{{titlesec}}
\usepackage{{hyperref}}
\usepackage{{xcolor}}
\usepackage{{etoolbox}}

\definecolor{{linkblue}}{{HTML}}{{245C8A}}
\hypersetup{{
  colorlinks=true,
  linkcolor=linkblue,
  citecolor=linkblue,
  urlcolor=linkblue,
  pdftitle={{Value Differencing Halves 4-Bit Quantization Damage in Attention}},
  pdfauthor={{David Gao}}
}}

\setlist{{nosep,leftmargin=1.35em}}
\setlength{{\parindent}}{{1em}}
\setlength{{\parskip}}{{0.12em}}
\setlength{{\tabcolsep}}{{4pt}}
\setlength{{\LTleft}}{{0pt}}
\setlength{{\LTright}}{{0pt}}
\AtBeginEnvironment{{longtable}}{{\footnotesize}}
\captionsetup{{font=small,labelfont=bf}}
\emergencystretch=3em
\titleformat{{\section}}{{\large\bfseries}}{{\thesection}}{{0.7em}}{{}}
\titleformat{{\subsection}}{{\normalsize\bfseries}}{{\thesubsection}}{{0.65em}}{{}}
\titlespacing*{{\section}}{{0pt}}{{1.35em}}{{0.55em}}
\titlespacing*{{\subsection}}{{0pt}}{{1.0em}}{{0.35em}}

\providecommand{{\tightlist}}{{\setlength{{\itemsep}}{{0pt}}\setlength{{\parskip}}{{0pt}}}}
\providecommand{{\pandocbounded}}[1]{{#1}}
\newcounter{{none}}
\makeatletter
\def\maxwidth{{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}}
\def\maxheight{{\ifdim\Gin@nat@height>0.72\textheight 0.72\textheight\else\Gin@nat@height\fi}}
\makeatother
\setkeys{{Gin}}{{width=\maxwidth,height=\maxheight,keepaspectratio}}

\title{{\textbf{{Value Differencing Halves 4-Bit Quantization Damage in Attention}}}}
\author{{David Gao}}
\date{{July 2026}}

\begin{{document}}
\maketitle

\begin{{abstract}}
{abstract}
\end{{abstract}}

\bibliographystyle{{plainnat}}

{body}

\end{{document}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--pandoc", default=shutil.which("pandoc"))
    args = parser.parse_args()
    if not args.pandoc:
        raise SystemExit("pandoc was not found; pass --pandoc /path/to/pandoc")

    markdown = args.source.read_text()
    abstract_md, body_md = split_manuscript(markdown)
    body_md = fold_figure_captions(body_md)
    body_md = normalize_headings(body_md)
    abstract_tex = pandoc_fragment(abstract_md, args.pandoc)
    body_tex = pandoc_fragment(body_md, args.pandoc, shift_headings=True)
    args.output.write_text(latex_document(abstract_tex, body_tex))


if __name__ == "__main__":
    main()
